name: earthquake
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - alembic=1.14.0
  - annotated-types=0.7.0
  - async-timeout=5.0.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.9.31
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.0
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - colorful=0.5.6
  - colorlog=6.9.0
  - coreforecast=0.0.14
  - cpython=3.12.7
  - cryptography=43.0.3
  - distlib=0.3.9
  - elfutils=0.192
  - filelock=3.16.1
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.8.8
  - google-api-core=2.22.0
  - google-auth=2.36.0
  - googleapis-common-protos=1.66.0
  - greenlet=3.1.1
  - grpcio=1.65.5
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libabseil=20240722.0
  - libarchive=3.7.4
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgrpc=1.65.5
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - libmicrohttpd=1.0.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libparquet=18.0.0
  - libprotobuf=5.27.5
  - libre2-11=2024.07.02
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.21.0
  - libtorch=2.4.1
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.49.2
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lightning-utilities=0.11.8
  - linkify-it-py=2.0.3
  - llvm-openmp=19.1.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.3.5
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - memray=1.14.0
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - neuralforecast=1.7.5
  - numpy=2.1.3
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openssl=3.4.0
  - optuna=4.1.0
  - orc=2.0.2
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - prometheus_client=0.21.0
  - proto-plus=1.25.0
  - protobuf=5.27.5
  - psutil=6.1.0
  - py-spy=0.4.0
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-lightning=2.4.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - ray-core=2.38.0
  - ray-default=2.38.0
  - ray-tune=2.38.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.4
  - rpds-py=0.21.0
  - rsa=4.9
  - s2n=1.5.6
  - setproctitle=1.3.3
  - setuptools=75.3.0
  - six=1.16.0
  - sleef=3.7
  - smart_open=7.0.5
  - snappy=1.2.1
  - sqlalchemy=2.0.36
  - sympy=1.13.3
  - tbb=2021.13.0
  - tensorboardx=2.6.2.2
  - textual=0.85.2
  - tk=8.6.13
  - torchmetrics=1.5.2
  - tqdm=4.67.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - uc-micro-py=1.0.3
  - urllib3=2.2.3
  - utilsforecast=0.2.8
  - virtualenv=20.21.0
  - wheel=0.45.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
